name: Changelog
version: 1.0.0
main: Electro\Changelog\Main
api: 3.14.2
author: Electro

commands:
  changelog:
    usage: /changelog
    aliases: [cl]
    description: "Open the changelogs of the Server"
